version: '3.4'

services:
  thegalaxyapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - POSTGRES_HOST=database
      - FRONT_APP_HOST=*

      - ACCESS_TOKEN_ISSUER=TheGalaxyApp
      - ACCESS_TOKEN_AUDIENCE=TheGalaxyApp
      - ACCESS_TOKEN_SECRET_KEY=00330755-0CA5-490D-9516-D8BDEF622636

      - POSTGRES_PASSWORD=postgres
      - PG_PRIMARY_USER=foregestore
      - PUBLIC_URL=http://localhost
      - PG_PRIMARY_PASSWORD=L0calPasw0rd
    ports:
      - "51209:8080"
      - "51208:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  thegalaxy-core:
    environment:
      - USER_ACCESS_LIFE_TIME=2
      - ACCESS_TOKEN_ISSUER=TheGalaxyApp
      - ACCESS_TOKEN_AUDIENCE=TheGalaxyApp
      - ACCESS_TOKEN_SECRET_KEY=00330755-0CA5-490D-9516-D8BDEF622636

  thegalaxy-database:
    environment:
      - DATABASE_CONNECTION=Server=service.database;Port=5432;Database=postgres;User Id=postgres;Password=postgres;
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  database:
    environment:
      - DATABASE_CONNECTION=Server=service.database;Port=5432;Database=galaxy-db;User Id=postgres;Password=postgres;
      - POSTGRES_PASSWORD=postgres
      - PG_PRIMARY_USER=foregestore
      - PG_PRIMARY_PASSWORD=L0calPasw0rd
    ports:
      - 5432:5432